---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

    - name: Webserver Instances
      ec2:
        key_name: frankfurt
        instance_type: t2.micro
        image: ami-194cdc76
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          for: summit
          role: webserver
          Name: webserverbyansible
        user_data: "{{ lookup('file', 'webserver.sh') }}"
        monitoring: no
        vpc_subnet_id: subnet-33b7b74b
        assign_public_ip: yes
        region: 'eu-central-1'
        state: present

    - name: Database Instances
      ec2:
        key_name: frankfurt
        instance_type: t2.micro
        image: ami-194cdc76
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          for: summit
          role: database
          Name: databasebyansible
        user_data: "{{ lookup('file', 'database.sh') }}"
        monitoring: no
        vpc_subnet_id: subnet-33b7b74b
        assign_public_ip: yes
        region: 'eu-central-1'
        state: present

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ansiblecreated
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Configure instance(s)
      hosts: launched
      user: ec2-user
      become: True
      gather_facts: True
      roles:
        - { role: "common.summit" }
